version: '3.1'

services:
  web:
    image: nginx
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "8090:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
